name: build and test
on: [push]
jobs:
  just_test:
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.22"
      - name: go test
        run: echo "Test skipped for this repo"
        # run: go test -v ./...
  test_build_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.22"
      - name: Get the version
        id: get_tag
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      # - name: go test
      #   run: go test -v ./...
      - name: build
        shell: bash
        run: |
          # Make an artifacts directory
          mkdir -p artifacts

          for arch in "amd64" "arm64"; do
            echo "Building for $os on $arch..."
            GOOS=linux GOARCH=$arch CGO_ENABLED=0 go build -a -ldflags="-X main.VersionNumber=${{ steps.get_tag.outputs.SOURCE_TAG }} -X main.VersionHash=${{ github.sha }}" -o ./artifacts/goofys_linux_${arch} .
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          body_path: .github/workflows/release_body.md
        env:
          GITHUB_TOKEN: ${{ github.token }}